---
- name: User
  include_tasks: plays/user.yml
  vars:
    group: "{{avax_group}}"
    gid: "{{avax_group_id}}"
    user: "{{avax_user}}"
    uid: "{{avax_user_id}}"
    user_group: "{{avax_group}}"
  tags: user

- name: Avax docker image
  include_tasks: roles/avax/tasks/docker.yml
  tags: docker

- name: Avax docker deploy
  include_tasks: roles/avax/tasks/deploy.yml
  tags: deploy,never
