---
- name: Create chainlink user and group 
  tags: user
  include_tasks: plays/user.yml
  vars:
    group: "{{chainlink_group}}"
    gid: "{{chainlink_group_id}}"
    user: "{{chainlink_user}}"
    uid: "{{chainlink_user_id}}"
    user_group: "{{chainlink_group}}"

#- name: Chainlink docker image
#  include_tasks: roles/chainlink/tasks/docker.yml
#  tags: docker

- name: Chainlink docker deploy
  include_tasks: roles/chainlink/tasks/deploy.yml
  tags: deploy,never
